/**
 * Hardcoded operation guide data extracted from OPERATION_GUIDE_FINAL.md
 *
 * This data is manually curated from the OPERATION_GUIDE_FINAL.md document
 * to ensure high-quality search results. In future versions, this can be
 * auto-generated from the markdown file.
 */

import { Operation } from './operationSchema';

export const OPERATIONS: Operation[] = [
  // ========== HOME (ホームページ) ==========
  {
    operationId: 'home-navigate-stage1',
    screen: 'Home',
    screenPath: '/',
    operationName: '「さっそく始める」ボタン',
    description: 'STAGE1 へ遷移。企業価値分析を開始します。',
    steps: [
      'ホーム画面を開く',
      'ヒーロー画面下部中央の「さっそく始める」ボタンをクリック',
      'STAGE1 へ遷移'
    ],
    permissions: ['Admin', 'Manager', 'Member'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage1'],
    keywords: ['さっそく', '始める', '遷移', 'stage1', '企業価値', '分析'],
    category: 'navigation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 24, endLine: 26 },
  },
  {
    operationId: 'home-navigate-report',
    screen: 'Home',
    screenPath: '/',
    operationName: '「レポート」ボタン',
    description: 'Report ページへ遷移。戦略成果物を確認します。',
    steps: [
      'ホーム画面を開く',
      'ヒーロー画面下部の「レポート」ボタンをクリック',
      'Report ページへ遷移'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: [],
    keywords: ['レポート', '成果物', '確認', 'report', 'pdf'],
    category: 'navigation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 25, endLine: 26 },
  },
  {
    operationId: 'home-pyramid-navigator',
    screen: 'Home',
    screenPath: '/',
    operationName: '戦略設計パネル（PyramidNavigator）',
    description: '左側カラムに STAGE1～STAGE6 の 6 ステージがピラミッド状に表示。各ステージをクリックしてジャンプできます。',
    steps: [
      'ホーム画面左側のピラミッドナビゲータを確認',
      'STAGE1～STAGE6 のいずれかをクリック',
      '該当ページへジャンプ'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage1', 'Stage2', 'Stage3', 'Stage4', 'Stage5', 'Stage6'],
    keywords: ['ナビゲータ', 'ピラミッド', 'ステージ', 'クリック', 'ジャンプ'],
    category: 'navigation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 26, endLine: 27 },
  },

  // ========== STAGE0 - アイスブレイク ==========
  {
    operationId: 'stage0-add-participant',
    screen: 'STAGE0 - アイスブレイク',
    screenPath: '/stage0',
    operationName: '参加者追加',
    description: '参加者名を入力して「追加」ボタンで参加者リストに追加します。',
    steps: [
      'STAGE0 ページを開く',
      '参加者名を入力欄に入力（最大 20 文字推奨）',
      '「追加」ボタンをクリック',
      '参加者がリストに追加される'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: 'text',
    savingMethod: 'none',
    relatedStages: ['Stage0'],
    keywords: ['参加者', '追加', '入力', 'アイスブレイク'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 67, endLine: 72 },
  },
  {
    operationId: 'stage0-start-roulette',
    screen: 'STAGE0 - アイスブレイク',
    screenPath: '/stage0',
    operationName: 'ルーレット抽選を開始',
    description: '「回す」ボタンで参加者とトピックをランダム抽選します。',
    steps: [
      'STAGE0 ページで参加者を追加後、「始める」ボタンをクリック',
      'ルーレット抽選フェーズへ遷移',
      '「回す」ボタンをクリック',
      '参加者とトピックがランダムに抽選される'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage0'],
    keywords: ['ルーレット', '抽選', '開始', '回す', 'アイスブレイク'],
    category: 'display',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 74, endLine: 79 },
  },

  // ========== STAGE1 - 企業価値分析 ==========
  {
    operationId: 'stage1-company-info-input',
    screen: 'STAGE1 - 企業価値分析',
    screenPath: '/stage1',
    operationName: '企業情報・事業内容を入力',
    description: '企業名、業種、事業説明、事業セグメント（複数）を入力します。',
    steps: [
      'STAGE1 ページを開く',
      '「企業情報・事業内容」セクションを見つける',
      '企業名と業種を入力',
      '事業説明をテキストエリアに入力',
      '「追加」ボタンでセグメント行を追加',
      'セグメント名、売上、営業利益、説明を入力'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage1'],
    keywords: ['企業', '情報', '事業', 'セグメント', '売上', '入力'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 128, endLine: 132 },
  },
  {
    operationId: 'stage1-finance-data-input',
    screen: 'STAGE1 - 企業価値分析',
    screenPath: '/stage1',
    operationName: '財務データを入力',
    description: 'PL・BS データを手入力またはファイルアップロードで入力します。',
    steps: [
      'STAGE1 ページの「財務データセクション」を開く',
      '全社 PL：売上、売上原価、営業利益などを各年分入力',
      '全社 BS：総資産、負債、純資産などを各年分入力',
      'またはExcel/CSVファイルをアップロード'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'number',
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage1'],
    keywords: ['財務', 'データ', 'PL', 'BS', '売上', '利益', '入力'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 134, endLine: 139 },
  },
  {
    operationId: 'stage1-issue-input',
    screen: 'STAGE1 - 企業価値分析',
    screenPath: '/stage1',
    operationName: '経営課題・機会を整理',
    description: '経営課題と機会を自由入力して STAGE2 へ進みます。',
    steps: [
      'STAGE1 ページ下部の「論点整理」セクションを開く',
      '経営課題・機会をテキストエリアに入力',
      '重点論点を列挙',
      '「STAGE2 へ」ボタンをクリック'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage1', 'Stage2'],
    keywords: ['課題', '機会', '論点', '整理', 'stage2'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 154, endLine: 158 },
  },

  // ========== STAGE2 - 全社戦略 ==========
  {
    operationId: 'stage2-answer-12-questions',
    screen: 'STAGE2 - 全社戦略',
    screenPath: '/stage2',
    operationName: '12 問テンプレートに回答',
    description: '4 章構成の 12 問に対して自由記述で回答します。',
    steps: [
      'STAGE2 ページを開く',
      '「入力」タブで 12 問テンプレートを確認',
      '各問に対して回答をテキスト入力（各 200～500 文字推奨）',
      '最大 2000 文字まで入力可能'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage2'],
    keywords: ['12問', '回答', '入力', 'テンプレート', '戦略', 'stage2'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 207, endLine: 212 },
  },
  {
    operationId: 'stage2-deep-dive-question',
    screen: 'STAGE2 - 全社戦略',
    screenPath: '/stage2',
    operationName: 'AI 掘り下げ質問を生成',
    description: '危機認識など 4 問に対して「掘り下げる」ボタンで AI がフォローアップ質問を生成します。',
    steps: [
      'STAGE2 の 12 問セクションを開く',
      '危機認識（ch0-q1）など対象問の「掘り下げる」ボタンをクリック',
      'AI がフォローアップ質問 1 問を自動生成',
      '掘り下げ質問に回答'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage2'],
    keywords: ['掘り下げ', 'AI', 'フォローアップ', '質問', '生成'],
    category: 'generation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 214, endLine: 219 },
  },
  {
    operationId: 'stage2-generate-draft',
    screen: 'STAGE2 - 全社戦略',
    screenPath: '/stage2',
    operationName: 'ドラフト戦略を生成',
    description: '12 問の回答から AI が 4 章構成のドラフト戦略書を自動生成します。',
    steps: [
      'STAGE2 ページの「戦略議論」タブを開く',
      '「議論をまとめてドラフトを生成」ボタンをクリック',
      'AI が 12 問の回答を分析',
      '4 章構成のドラフト戦略書が生成される'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage2'],
    keywords: ['ドラフト', '生成', 'AI', '戦略', '4章'],
    category: 'generation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 223, endLine: 229 },
  },
  {
    operationId: 'stage2-generate-final',
    screen: 'STAGE2 - 全社戦略',
    screenPath: '/stage2',
    operationName: '最終版戦略書を生成',
    description: 'ドラフトをブラッシュアップして構造化された最終版戦略書を生成します。',
    steps: [
      'STAGE2 の「最終確定」タブを開く',
      'ドラフト生成完了後、「最終版を生成」ボタンをクリック',
      'AI がドラフトを最適化',
      '最終版ストーリーが構造化データで返される'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'auto',
    debounceTime: 1200,
    relatedStages: ['Stage2'],
    keywords: ['最終版', '生成', 'AI', '戦略書', 'ブラッシュアップ'],
    category: 'generation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 233, endLine: 238 },
  },
  {
    operationId: 'stage2-confirm',
    screen: 'STAGE2 - 全社戦略',
    screenPath: '/stage2',
    operationName: 'STAGE2 を確定',
    description: '最終版戦略書を確定して Supabase に保存し、STAGE3 へ遷移します。',
    steps: [
      'STAGE2 の「最終確定」タブで最終版を確認',
      '必要に応じて編集',
      '「確定」ボタンをクリック',
      'Supabase に保存され STAGE3 へ自動遷移'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'manual',
    relatedStages: ['Stage2', 'Stage3'],
    keywords: ['確定', '保存', '最終版', 'stage3', '遷移'],
    category: 'save',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 245, endLine: 249 },
  },

  // ========== STAGE3 - Cascade ==========
  {
    operationId: 'stage3-add-department',
    screen: 'STAGE3 - 事業・部門別戦略',
    screenPath: '/cascade',
    operationName: '部門を追加',
    description: '「+ 部門を追加」ボタンで新しい部門をリストに追加します。',
    steps: [
      'STAGE3（Cascade）ページを開く',
      '「+ 部門を追加」ボタンをクリック',
      '部門名とミッション（説明）を入力',
      '「追加」ボタンで部門をリストに追加'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'manual',
    relatedStages: ['Stage3'],
    keywords: ['部門', '追加', '新規', 'ミッション'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 303, endLine: 307 },
  },
  {
    operationId: 'stage3-generate-cascade',
    screen: 'STAGE3 - 事業・部門別戦略',
    screenPath: '/cascade',
    operationName: 'AI で部門別タタキ台を生成',
    description: 'STAGE2 の戦略と部門ミッションから AI が重点テーマ・プロジェクト・KPI を自動提案します。',
    steps: [
      'STAGE3 ページで部門を追加',
      '部門カード内の「AI で部門別タタキ台を提案」ボタン（Sparkles アイコン）をクリック',
      'AI が STAGE2 最終ストーリーと部門ミッションを分析',
      '重点テーマ・プロジェクト・KPI 候補が自動生成'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'manual',
    relatedStages: ['Stage2', 'Stage3'],
    keywords: ['AI', 'タタキ台', '提案', '生成', 'テーマ', 'KPI'],
    category: 'generation',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 332, endLine: 338 },
  },
  {
    operationId: 'stage3-save',
    screen: 'STAGE3 - 事業・部門別戦略',
    screenPath: '/cascade',
    operationName: 'STAGE3 を保存',
    description: '全部門・プロジェクト・KPI・期待インパクト データを Supabase に保存します。',
    steps: [
      'STAGE3 ページで部門とプロジェクトを入力',
      'KPI と期待インパクトを確認',
      'ページ下部の「保存」ボタンをクリック',
      'データが Supabase に送信され、「保存しました」メッセージが表示'
    ],
    permissions: ['Admin', 'Manager'],
    viewerCanAccess: false,
    inputRequired: null,
    savingMethod: 'manual',
    relatedStages: ['Stage3'],
    keywords: ['保存', 'STAGE3', 'Supabase', 'データ'],
    category: 'save',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 344, endLine: 348 },
  },

  // ========== STAGE4 - OKR ==========
  {
    operationId: 'stage4-select-department',
    screen: 'STAGE4 - 実行計画策定',
    screenPath: '/stage4',
    operationName: '部門を選択',
    description: '左側の部門リストから対象部門をクリックして詳細パネルを表示します。',
    steps: [
      'STAGE4 ページを開く',
      '左側の部門リスト（Department Selector）を確認',
      '編集する部門をクリック',
      '右側に詳細パネルが展開される'
    ],
    permissions: ['Admin', 'Manager', 'Member'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage4'],
    keywords: ['部門', '選択', 'STAGE4', '詳細', 'パネル'],
    category: 'display',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 394, endLine: 398 },
  },
  {
    operationId: 'stage4-kpi-edit',
    screen: 'STAGE4 - 実行計画策定',
    screenPath: '/stage4',
    operationName: 'KPI を追加・削除',
    description: 'プロジェクトの KPI ターゲットを追加または削除します。',
    steps: [
      'STAGE4 で部門を選択',
      'プロジェクト詳細を開く',
      '「KPI ターゲット」セクションの「追加」ボタンをクリック',
      '新しい KPI（名称 + 目標値）を入力',
      '不要な KPI は赤いゴミ箱アイコンで削除'
    ],
    permissions: ['Admin', 'Manager', 'Member'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'auto',
    debounceTime: 1500,
    relatedStages: ['Stage4'],
    keywords: ['KPI', '追加', '削除', '目標値', 'STAGE4'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 406, endLine: 411 },
  },
  {
    operationId: 'stage4-status-update',
    screen: 'STAGE4 - 実行計画策定',
    screenPath: '/stage4',
    operationName: 'ステータスを更新',
    description: '部門ごとの実行ステータスを「Draft」「Review」「Approved」から選択します。',
    steps: [
      'STAGE4 ページで部門を選択',
      'ステータス管理セクション（StatusSelect）を確認',
      'ドロップダウンをクリック',
      '「Draft」（下書き）/ 「Review」（レビュー中）/ 「Approved」（承認済み）から選択'
    ],
    permissions: ['Admin', 'Manager', 'Member'],
    viewerCanAccess: false,
    inputRequired: 'select',
    savingMethod: 'auto',
    debounceTime: 1500,
    relatedStages: ['Stage4'],
    keywords: ['ステータス', '状態', '更新', 'Draft', 'Review', 'Approved'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 427, endLine: 435 },
  },

  // ========== STAGE5 - Execution ==========
  {
    operationId: 'stage5-log-progress',
    screen: 'STAGE5 - 実行支援',
    screenPath: '/execution',
    operationName: '進捗ログを記録',
    description: '今月の進捗サマリー、課題・懸念点、次の施策を入力して保存します。',
    steps: [
      'STAGE5 ページで部門・プロジェクトを選択',
      '「進捗を記録」ボタンをクリック',
      'テキストエリアで進捗サマリーを入力（最大 2000 文字）',
      '課題・懸念点、次の施策を入力',
      '「記録する」ボタンで Supabase に保存'
    ],
    permissions: ['Admin', 'Manager', 'Member'],
    viewerCanAccess: false,
    inputRequired: 'text',
    savingMethod: 'manual',
    relatedStages: ['Stage5'],
    keywords: ['進捗', 'ログ', '記録', '課題', '施策'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 510, endLine: 515 },
  },
  {
    operationId: 'stage5-ceo-chat',
    screen: 'STAGE5 - 実行支援',
    screenPath: '/execution',
    operationName: 'CEO コンサルタントに相談',
    description: '進捗ログやプロジェクト情報に基づいて AI コンサルタントに助言を求めます。',
    steps: [
      'STAGE5 ページを開く',
      '「CEO に相談」ボタンをクリック',
      'AI（CEO コンサルタント）からの助言を チャット形式で受け取る',
      '提案を参考に STAGE3/4 で調整'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage5'],
    keywords: ['CEO', 'AI', '相談', 'チャット', '助言'],
    category: 'display',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 529, endLine: 533 },
  },

  // ========== STAGE6 - 業績シミュレーション ==========
  {
    operationId: 'stage6-view-impact',
    screen: 'STAGE6 - 業績シミュレーション',
    screenPath: '/stage6',
    operationName: '業績インパクトを確認',
    description: 'プロジェクト別の売上・営業利益寄与を棒グラフ・テーブルで可視化。',
    steps: [
      'STAGE6 ページを開く',
      '「業績インパクト」タブを確認',
      'プロジェクト別の目標寄与 vs 実績寄与を表示',
      '見直し候補のプロジェクトを確認'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage6'],
    keywords: ['インパクト', '売上', '利益', '寄与', '達成率'],
    category: 'display',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 586, endLine: 590 },
  },

  // ========== ORG-TRANSFORMATION ==========
  {
    operationId: 'org-transformation-input',
    screen: 'ORG-TRANSFORMATION',
    screenPath: '/org-transformation',
    operationName: '違和感・もやもやを入力',
    description: '感じている違和感やもやもや、および自分の認識をテキスト入力します。',
    steps: [
      'ORG-TRANSFORMATION ページを開く',
      '「違和感・もやもやを入力」セクションで対象テーマを入力',
      '「あなたは、このテーマについてどのような認識を持っていますか？」に回答',
      '対話相手をドロップダウンから選択'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: 'text',
    savingMethod: 'manual',
    relatedStages: [],
    keywords: ['違和感', 'もやもや', '認識', '入力', '対話'],
    category: 'input',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 654, endLine: 662 },
  },
  {
    operationId: 'org-transformation-request',
    screen: 'ORG-TRANSFORMATION',
    screenPath: '/org-transformation',
    operationName: 'すり合わせを依頼',
    description: 'AI 分析結果を確認後、共有方法を選択して「すり合わせを依頼」ボタンで保存します。',
    steps: [
      'ORG-TRANSFORMATION で STEP1～4 を完了',
      '「すり合わせ依頼」セクションで共有方法を選択（「匿名で共有」「管理者にのみ共有」「名前を出して共有」）',
      '「すり合わせを依頼」ボタンをクリック'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: 'select',
    savingMethod: 'manual',
    relatedStages: [],
    keywords: ['すり合わせ', '依頼', '共有', '匿名', '管理者'],
    category: 'save',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 677, endLine: 685 },
  },

  // ========== Report ==========
  {
    operationId: 'report-view-list',
    screen: 'Report',
    screenPath: '/report',
    operationName: 'レポート一覧を確認',
    description: 'STAGE2 戦略書、戦略実行レポート、中計戦略書の 3 つのレポートカードを表示。',
    steps: [
      'Report ページを開く',
      '3 つのレポートカードを確認：',
      '  - 全社戦略書（STAGE2）',
      '  - 戦略実行レポート（STAGE5-6）',
      '  - 中計戦略書（STAGE1-4）',
      '各カードをクリックして詳細へ'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: [],
    keywords: ['レポート', '一覧', '表示', '戦略書', 'Report'],
    category: 'display',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 740, endLine: 753 },
  },
  {
    operationId: 'report-stage2-pdf-download',
    screen: 'Report',
    screenPath: '/report/stage2-strategy',
    operationName: 'STAGE2 戦略書を PDF で出力',
    description: 'STAGE2 全社戦略書の PDF ダウンロード。ページ右上の「PDF 出力」ボタンをクリック。',
    steps: [
      'Report ページから「全社戦略書」をクリック',
      '/report/stage2-strategy ページが開く',
      'ページ右上の「PDF 出力」ボタンをクリック',
      'PDF ファイルがダウンロード される'
    ],
    permissions: ['Admin', 'Manager', 'Member', 'Viewer'],
    viewerCanAccess: true,
    inputRequired: null,
    savingMethod: 'none',
    relatedStages: ['Stage2'],
    keywords: ['PDF', '出力', 'ダウンロード', 'STAGE2', '戦略書'],
    category: 'export',
    docReference: { file: 'OPERATION_GUIDE_FINAL.md', startLine: 758, endLine: 759 },
  },
];
