-- Add swot_suggestions column to strategy_data table
-- Purpose: Store AI-generated Opportunity/Threat suggestions for STAGE2 SWOT analysis
-- Structure: { opportunity?: string[], threat?: string[], generatedAt?: string }

ALTER TABLE strategy_data
ADD COLUMN IF NOT EXISTS swot_suggestions JSONB;

-- Add comment describing the column structure
COMMENT ON COLUMN strategy_data.swot_suggestions IS
  'STAGE2 SWOT AI-generated suggestions. Structure: { opportunity?: string[], threat?: string[], generatedAt?: string }. Generated by /api/generate-ot endpoint.';

-- Verify column was added
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'strategy_data'
      AND column_name = 'swot_suggestions'
  ) THEN
    RAISE NOTICE 'Column swot_suggestions successfully added to strategy_data';
  ELSE
    RAISE EXCEPTION 'Failed to add swot_suggestions column';
  END IF;
END $$;
